columns_all = [ 'tripid',
                'additional_fare',
                'duration',
                'meter_waiting',
                'meter_waiting_fare',
                'meter_waiting_till_pickup',
                'pickup_time',
                'drop_time',
                'pick_lat',
                'pick_lon',
                'drop_lat',
                'drop_lon',
                'fare',
                'label']